# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('image', models.URLField()),
                ('is_active', models.BooleanField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelUserCouponDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Coupon')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='storetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreType'),
        ),
        migrations.AddField(
            model_name='relusercoupondonation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
    ]
