# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('stores', '0002_auto_20171119_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='organization',
        ),
        migrations.AddField(
            model_name='coupon',
            name='organization',
            field=models.ManyToManyField(to='organizations.Organization'),
        ),
    ]
