# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start', models.DecimalField(decimal_places=2, max_digits=6)),
                ('end', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CPT', 'Completed'), ('PND', 'Pending'), ('CNCL', 'Cancelled')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=80)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='RelDonationCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancellation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Cancellation')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Donation')),
            ],
        ),
    ]
